In [1]:
import pandas as pd
import os
from pathlib import Path

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)
pd.set_option("display.width", 120)

In [2]:
# Get the project root directory
PROJECT_ROOT = Path.cwd().parent

# Raw data directory
RAW_DATA_PATH = PROJECT_ROOT / "data" / "raw"

print("Project Root:", PROJECT_ROOT)
print("Raw Data Path:", RAW_DATA_PATH)

Project Root: d:\cart2insights
Raw Data Path: d:\cart2insights\data\raw

In [3]:
DATASETS = {
    "customers": "olist_customers_dataset.csv",
    "geolocation": "olist_geolocation_dataset.csv",
    "order_items": "olist_order_items_dataset.csv",
    "order_payments": "olist_order_payments_dataset.csv",
    "order_reviews": "olist_order_reviews_dataset.csv",
    "orders": "olist_orders_dataset.csv",
    "products": "olist_products_dataset.csv",
    "sellers": "olist_sellers_dataset.csv",
    "translation": "product_category_name_translation.csv"
}

print(f"Total datasets expected: {len(DATASETS)}")

for name, filename in DATASETS.items():
    print(f"{name:20} -> {filename}")

Total datasets expected: 9
customers            -> olist_customers_dataset.csv
geolocation          -> olist_geolocation_dataset.csv
order_items          -> olist_order_items_dataset.csv
order_payments       -> olist_order_payments_dataset.csv
order_reviews        -> olist_order_reviews_dataset.csv
orders               -> olist_orders_dataset.csv
products             -> olist_products_dataset.csv
sellers              -> olist_sellers_dataset.csv
translation          -> product_category_name_translation.csv

In [4]:
data = {}

for table_name, filename in DATASETS.items():
    file_path = RAW_DATA_PATH / filename
    
    if not file_path.exists():
        print(f"WARNING: File not found -> {file_path}")
        continue
    
    data[table_name] = pd.read_csv(file_path, low_memory=False)

print(f"Datasets successfully loaded: {len(data)}")

Datasets successfully loaded: 9

In [5]:
shape_summary = []

for table_name, df in data.items():
    shape_summary.append({
        "table": table_name,
        "rows": df.shape[0],
        "columns": df.shape[1]
    })

shape_df = pd.DataFrame(shape_summary)

display(
    shape_df.sort_values("rows", ascending=False).reset_index(drop=True)
)

            table     rows  columns
0     geolocation  1000163        5
1     order_items   112650        7
2  order_payments   103886        5
3       customers    99441        5
4          orders    99441        8
5   order_reviews    99224        7
6        products    32951        9
7         sellers     3095        4
8     translation       71        2

In [6]:
for table_name, df in data.items():
    print("\n" + "=" * 80)
    print(f"TABLE: {table_name}")
    print("=" * 80)
    
    print("Columns:")
    for column in df.columns:
        print(f" - {column}")

================================================================================
TABLE: customers
================================================================================
Columns:
 - customer_id
 - customer_unique_id
 - customer_zip_code_prefix
 - customer_city
 - customer_state

================================================================================
TABLE: geolocation
================================================================================
Columns:
 - geolocation_zip_code_prefix
 - geolocation_lat
 - geolocation_lng
 - geolocation_city
 - geolocation_state

================================================================================
TABLE: order_items
================================================================================
Columns:
 - order_id
 - order_item_id
 - product_id
 - seller_id
 - shipping_limit_date
 - price
 - freight_value

================================================================================
TABLE: order_payments
================================================================================
Columns:
 - order_id
 - payment_sequential
 - payment_type
 - payment_installments
 - payment_value

================================================================================
TABLE: order_reviews
================================================================================
Columns:
 - review_id
 - order_id
 - review_score
 - review_comment_title
 - review_comment_message
 - review_creation_date
 - review_answer_timestamp

================================================================================
TABLE: orders
================================================================================
Columns:
 - order_id
 - customer_id
 - order_status
 - order_purchase_timestamp
 - order_approved_at
 - order_delivered_carrier_date
 - order_delivered_customer_date
 - order_estimated_delivery_date

================================================================================
TABLE: products
================================================================================
Columns:
 - product_id
 - product_category_name
 - product_name_lenght
 - product_description_lenght
 - product_photos_qty
 - product_weight_g
 - product_length_cm
 - product_height_cm
 - product_width_cm

================================================================================
TABLE: sellers
================================================================================
Columns:
 - seller_id
 - seller_zip_code_prefix
 - seller_city
 - seller_state

================================================================================
TABLE: translation
================================================================================
Columns:
 - product_category_name
 - product_category_name_english

In [7]:
for table_name, df in data.items():
    print("\n" + "=" * 80)
    print(f"TABLE: {table_name}")
    print("=" * 80)
    
    display(df.head(5))

================================================================================
TABLE: customers
================================================================================

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

================================================================================
TABLE: geolocation
================================================================================

   geolocation_zip_code_prefix  geolocation_lat  geolocation_lng geolocation_city geolocation_state
0                         1037       -23.545621       -46.639292        sao paulo                SP
1                         1046       -23.546081       -46.644820        sao paulo                SP
2                         1046       -23.546129       -46.642951        sao paulo                SP
3                         1041       -23.544392       -46.639499        sao paulo                SP
4                         1035       -23.541578       -46.641607        sao paulo                SP

================================================================================
TABLE: order_items
================================================================================

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14

================================================================================
TABLE: order_payments
================================================================================

                           order_id  payment_sequential payment_type  payment_installments  payment_value
0  b81ef226f3fe1789b1e8b2acac839d17                   1  credit_card                     8          99.33
1  a9810da82917af2d9aefd1278f1dcfa0                   1  credit_card                     1          24.39
2  25e8ea4e93396b6fa0d3dd708e76c1bd                   1  credit_card                     1          65.71
3  ba78997921bbcdc1373bb41e913ab953                   1  credit_card                     8         107.78
4  42fdf880ba16b47b59251dd489d4441a                   1  credit_card                     2         128.45

================================================================================
TABLE: order_reviews
================================================================================

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,NaN,NaN,2018-01-18 00:00:00,2018-01-18 21:46:59
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,NaN,NaN,2018-03-10 00:00:00,2018-03-11 03:05:13
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,NaN,NaN,2018-02-17 00:00:00,2018-02-18 14:36:24
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,NaN,Recebi bem antes do prazo estipulado.,2017-04-21 00:00:00,2017-04-21 22:02:06
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,NaN,Parabéns lojas lannister adorei comprar pela I...,2018-03-01 00:00:00,2018-03-02 10:26:53

================================================================================
TABLE: orders
================================================================================

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

================================================================================
TABLE: products
================================================================================

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0

================================================================================
TABLE: sellers
================================================================================

                          seller_id  seller_zip_code_prefix        seller_city seller_state
0  3442f8959a84dea7ee197c632cb2df15                   13023           campinas           SP
1  d1b65fc7debc3361ea86b5f14c68d2e2                   13844         mogi guacu           SP
2  ce3ad9de960102d0677a81f5d0bb7b2d                   20031     rio de janeiro           RJ
3  c0f3eea2e14555b6faeea3dd58c1b1c3                    4195          sao paulo           SP
4  51a04a8a6bdcb23deccc82b0b80742cf                   12914  braganca paulista           SP

================================================================================
TABLE: translation
================================================================================

    product_category_name product_category_name_english
0            beleza_saude                 health_beauty
1  informatica_acessorios         computers_accessories
2              automotivo                          auto
3         cama_mesa_banho                bed_bath_table
4        moveis_decoracao               furniture_decor

In [8]:
for table_name, df in data.items():
    print("\n" + "=" * 80)
    print(f"TABLE: {table_name}")
    print("=" * 80)
    
    display(df.head(5))

================================================================================
TABLE: customers
================================================================================

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

================================================================================
TABLE: geolocation
================================================================================

   geolocation_zip_code_prefix  geolocation_lat  geolocation_lng geolocation_city geolocation_state
0                         1037       -23.545621       -46.639292        sao paulo                SP
1                         1046       -23.546081       -46.644820        sao paulo                SP
2                         1046       -23.546129       -46.642951        sao paulo                SP
3                         1041       -23.544392       -46.639499        sao paulo                SP
4                         1035       -23.541578       -46.641607        sao paulo                SP

================================================================================
TABLE: order_items
================================================================================

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14

================================================================================
TABLE: order_payments
================================================================================

                           order_id  payment_sequential payment_type  payment_installments  payment_value
0  b81ef226f3fe1789b1e8b2acac839d17                   1  credit_card                     8          99.33
1  a9810da82917af2d9aefd1278f1dcfa0                   1  credit_card                     1          24.39
2  25e8ea4e93396b6fa0d3dd708e76c1bd                   1  credit_card                     1          65.71
3  ba78997921bbcdc1373bb41e913ab953                   1  credit_card                     8         107.78
4  42fdf880ba16b47b59251dd489d4441a                   1  credit_card                     2         128.45

================================================================================
TABLE: order_reviews
================================================================================

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,NaN,NaN,2018-01-18 00:00:00,2018-01-18 21:46:59
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,NaN,NaN,2018-03-10 00:00:00,2018-03-11 03:05:13
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,NaN,NaN,2018-02-17 00:00:00,2018-02-18 14:36:24
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,NaN,Recebi bem antes do prazo estipulado.,2017-04-21 00:00:00,2017-04-21 22:02:06
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,NaN,Parabéns lojas lannister adorei comprar pela I...,2018-03-01 00:00:00,2018-03-02 10:26:53

================================================================================
TABLE: orders
================================================================================

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

================================================================================
TABLE: products
================================================================================

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0

================================================================================
TABLE: sellers
================================================================================

                          seller_id  seller_zip_code_prefix        seller_city seller_state
0  3442f8959a84dea7ee197c632cb2df15                   13023           campinas           SP
1  d1b65fc7debc3361ea86b5f14c68d2e2                   13844         mogi guacu           SP
2  ce3ad9de960102d0677a81f5d0bb7b2d                   20031     rio de janeiro           RJ
3  c0f3eea2e14555b6faeea3dd58c1b1c3                    4195          sao paulo           SP
4  51a04a8a6bdcb23deccc82b0b80742cf                   12914  braganca paulista           SP

================================================================================
TABLE: translation
================================================================================

    product_category_name product_category_name_english
0            beleza_saude                 health_beauty
1  informatica_acessorios         computers_accessories
2              automotivo                          auto
3         cama_mesa_banho                bed_bath_table
4        moveis_decoracao               furniture_decor

In [9]:
dtype_summary = []

for table_name, df in data.items():
    for column in df.columns:
        dtype_summary.append({
            "table": table_name,
            "column": column,
            "dtype": str(df[column].dtype)
        })

dtype_df = pd.DataFrame(dtype_summary)

display(dtype_df)

             table                         column    dtype
0        customers                    customer_id      str
1        customers             customer_unique_id      str
2        customers       customer_zip_code_prefix    int64
3        customers                  customer_city      str
4        customers                 customer_state      str
5      geolocation    geolocation_zip_code_prefix    int64
6      geolocation                geolocation_lat  float64
7      geolocation                geolocation_lng  float64
8      geolocation               geolocation_city      str
9      geolocation              geolocation_state      str
10     order_items                       order_id      str
11     order_items                  order_item_id    int64
12     order_items                     product_id      str
13     order_items                      seller_id      str
14     order_items            shipping_limit_date      str
15     order_items                          price  float64
16     order_items                  freight_value  float64
17  order_payments                       order_id      str
18  order_payments             payment_sequential    int64
19  order_payments                   payment_type      str
20  order_payments           payment_installments    int64
21  order_payments                  payment_value  float64
22   order_reviews                      review_id      str
23   order_reviews                       order_id      str
24   order_reviews                   review_score    int64
25   order_reviews           review_comment_title      str
26   order_reviews         review_comment_message      str
27   order_reviews           review_creation_date      str
28   order_reviews        review_answer_timestamp      str
29          orders                       order_id      str
30          orders                    customer_id      str
31          orders                   order_status      str
32          orders       order_purchase_timestamp      str
33          orders              order_approved_at      str
34          orders   order_delivered_carrier_date      str
35          orders  order_delivered_customer_date      str
36          orders  order_estimated_delivery_date      str
37        products                     product_id      str
38        products          product_category_name      str
39        products            product_name_lenght  float64
40        products     product_description_lenght  float64
41        products             product_photos_qty  float64
42        products               product_weight_g  float64
43        products              product_length_cm  float64
44        products              product_height_cm  float64
45        products               product_width_cm  float64
46         sellers                      seller_id      str
47         sellers         seller_zip_code_prefix    int64
48         sellers                    seller_city      str
49         sellers                   seller_state      str
50     translation          product_category_name      str
51     translation  product_category_name_english      str

In [10]:
dataset_summary = []

for table_name, df in data.items():
    dataset_summary.append({
        "table": table_name,
        "rows": df.shape[0],
        "columns": df.shape[1],
        "total_cells": df.size,
        "duplicate_rows": df.duplicated().sum(),
        "missing_cells": df.isnull().sum().sum()
    })

dataset_summary_df = pd.DataFrame(dataset_summary)

display(dataset_summary_df)

            table     rows  columns  total_cells  duplicate_rows  missing_cells
0       customers    99441        5       497205               0              0
1     geolocation  1000163        5      5000815          261831              0
2     order_items   112650        7       788550               0              0
3  order_payments   103886        5       519430               0              0
4   order_reviews    99224        7       694568               0         145903
5          orders    99441        8       795528               0           4908
6        products    32951        9       296559               0           2448
7         sellers     3095        4        12380               0              0
8     translation       71        2          142               0              0

In [11]:
PRIMARY_KEYS = {
    "customers": ["customer_id"],
    "geolocation": ["geolocation_zip_code_prefix"],
    "order_items": ["order_id", "order_item_id"],
    "order_payments": ["order_id", "payment_sequential"],
    "order_reviews": ["review_id"],
    "orders": ["order_id"],
    "products": ["product_id"],
    "sellers": ["seller_id"],
    "translation": ["product_category_name"]
}

primary_key_summary = []

for table_name, keys in PRIMARY_KEYS.items():
    if table_name not in data:
        continue
    
    df = data[table_name]
    
    for key in keys:
        if key not in df.columns:
            primary_key_summary.append({
                "table": table_name,
                "key": key,
                "exists": False,
                "unique": None,
                "null_count": None
            })
            continue
        
        primary_key_summary.append({
            "table": table_name,
            "key": key,
            "exists": True,
            "unique": df[key].is_unique,
            "null_count": df[key].isnull().sum()
        })

primary_key_df = pd.DataFrame(primary_key_summary)

display(primary_key_df)

             table                          key  exists  unique  null_count
0        customers                  customer_id    True    True           0
1      geolocation  geolocation_zip_code_prefix    True   False           0
2      order_items                     order_id    True   False           0
3      order_items                order_item_id    True   False           0
4   order_payments                     order_id    True   False           0
5   order_payments           payment_sequential    True   False           0
6    order_reviews                    review_id    True   False           0
7           orders                     order_id    True    True           0
8         products                   product_id    True    True           0
9          sellers                    seller_id    True    True           0
10     translation        product_category_name    True    True           0

In [12]:
RELATIONSHIPS = [
    {
        "child_table": "orders",
        "child_column": "customer_id",
        "parent_table": "customers",
        "parent_column": "customer_id"
    },
    {
        "child_table": "order_items",
        "child_column": "order_id",
        "parent_table": "orders",
        "parent_column": "order_id"
    },
    {
        "child_table": "order_items",
        "child_column": "product_id",
        "parent_table": "products",
        "parent_column": "product_id"
    },
    {
        "child_table": "order_items",
        "child_column": "seller_id",
        "parent_table": "sellers",
        "parent_column": "seller_id"
    },
    {
        "child_table": "order_payments",
        "child_column": "order_id",
        "parent_table": "orders",
        "parent_column": "order_id"
    },
    {
        "child_table": "order_reviews",
        "child_column": "order_id",
        "parent_table": "orders",
        "parent_column": "order_id"
    },
    {
        "child_table": "products",
        "child_column": "product_category_name",
        "parent_table": "translation",
        "parent_column": "product_category_name"
    }
]

relationships_df = pd.DataFrame(RELATIONSHIPS)

display(relationships_df)

      child_table           child_column parent_table          parent_column
0          orders            customer_id    customers            customer_id
1     order_items               order_id       orders               order_id
2     order_items             product_id     products             product_id
3     order_items              seller_id      sellers              seller_id
4  order_payments               order_id       orders               order_id
5   order_reviews               order_id       orders               order_id
6        products  product_category_name  translation  product_category_name

In [13]:
relationship_checks = []

for relationship in RELATIONSHIPS:
    
    child_table = relationship["child_table"]
    child_column = relationship["child_column"]
    parent_table = relationship["parent_table"]
    parent_column = relationship["parent_column"]
    
    child_exists = (
        child_table in data
        and child_column in data[child_table].columns
    )
    
    parent_exists = (
        parent_table in data
        and parent_column in data[parent_table].columns
    )
    
    relationship_checks.append({
        "child_table": child_table,
        "child_column": child_column,
        "parent_table": parent_table,
        "parent_column": parent_column,
        "child_column_exists": child_exists,
        "parent_column_exists": parent_exists
    })

relationship_check_df = pd.DataFrame(relationship_checks)

display(relationship_check_df)

,child_table,child_column,parent_table,parent_column,child_column_exists,parent_column_exists
0,orders,customer_id,customers,customer_id,True,True
1,order_items,order_id,orders,order_id,True,True
2,order_items,product_id,products,product_id,True,True
3,order_items,seller_id,sellers,seller_id,True,True
4,order_payments,order_id,orders,order_id,True,True
5,order_reviews,order_id,orders,order_id,True,True
6,products,product_category_name,translation,product_category_name,True,True

In [14]:
data_dictionary = []

for table_name, df in data.items():
    for column in df.columns:
        data_dictionary.append({
            "table": table_name,
            "column": column,
            "data_type": str(df[column].dtype),
            "non_null_count": df[column].notna().sum(),
            "null_count": df[column].isna().sum(),
            "unique_values": df[column].nunique(dropna=True),
            "example_value": df[column].dropna().iloc[0]
                if df[column].notna().any()
                else None
        })

data_dictionary_df = pd.DataFrame(data_dictionary)

display(data_dictionary_df)

,table,column,data_type,non_null_count,null_count,unique_values,example_value
0,customers,customer_id,str,99441,0,99441,06b8999e2fba1a1fbc88172c00ba8bc7
1,customers,customer_unique_id,str,99441,0,96096,861eff4711a542e4b93843c6dd7febb0
2,customers,customer_zip_code_prefix,int64,99441,0,14994,14409
3,customers,customer_city,str,99441,0,4119,franca
4,customers,customer_state,str,99441,0,27,SP
5,geolocation,geolocation_zip_code_prefix,int64,1000163,0,19015,1037
6,geolocation,geolocation_lat,float64,1000163,0,717360,-23.545621
7,geolocation,geolocation_lng,float64,1000163,0,717613,-46.639292
8,geolocation,geolocation_city,str,1000163,0,8011,sao paulo
9,geolocation,geolocation_state,str,1000163,0,27,SP
10,order_items,order_id,str,112650,0,98666,00010242fe8c5a6d1ba2dd792cb16214
11,order_items,order_item_id,int64,112650,0,21,1
12,order_items,product_id,str,112650,0,32951,4244733e06e7ecb4970a6e2683c13e61
13,order_items,seller_id,str,112650,0,3095,48436dade18ac8b2bce089ec2a041202
14,order_items,shipping_limit_date,str,112650,0,93318,2017-09-19 09:45:35
15,order_items,price,float64,112650,0,5968,58.9
16,order_items,freight_value,float64,112650,0,6999,13.29
17,order_payments,order_id,str,103886,0,99440,b81ef226f3fe1789b1e8b2acac839d17
18,order_payments,payment_sequential,int64,103886,0,29,1
19,order_payments,payment_type,str,103886,0,5,credit_card
20,order_payments,payment_installments,int64,103886,0,24,8
21,order_payments,payment_value,float64,103886,0,29077,99.33
22,order_reviews,review_id,str,99224,0,98410,7bc2406110b926393aa56f80a40eba40
23,order_reviews,order_id,str,99224,0,98673,73fc7af87114b39712e6da79b0a377eb
24,order_reviews,review_score,int64,99224,0,5,4
25,order_reviews,review_comment_title,str,11568,87656,4527,recomendo
26,order_reviews,review_comment_message,str,40977,58247,36159,Recebi bem antes do prazo estipulado.
27,order_reviews,review_creation_date,str,99224,0,636,2018-01-18 00:00:00
28,order_reviews,review_answer_timestamp,str,99224,0,98248,2018-01-18 21:46:59
29,orders,order_id,str,99441,0,99441,e481f51cbdc54678b7cc49136f2d6af7
30,orders,customer_id,str,99441,0,99441,9ef432eb6251297304e76186b10a928d
31,orders,order_status,str,99441,0,8,delivered
32,orders,order_purchase_timestamp,str,99441,0,98875,2017-10-02 10:56:33
33,orders,order_approved_at,str,99281,160,90733,2017-10-02 11:07:15
34,orders,order_delivered_carrier_date,str,97658,1783,81018,2017-10-04 19:55:00
35,orders,order_delivered_customer_date,str,96476,2965,95664,2017-10-10 21:25:13
36,orders,order_estimated_delivery_date,str,99441,0,459,2017-10-18 00:00:00
37,products,product_id,str,32951,0,32951,1e9e8ef04dbcff4541ed26657ea517e5
38,products,product_category_name,str,32341,610,73,perfumaria
39,products,product_name_lenght,float64,32341,610,66,40.0
40,products,product_description_lenght,float64,32341,610,2960,287.0
41,products,product_photos_qty,float64,32341,610,19,1.0
42,products,product_weight_g,float64,32949,2,2204,225.0
43,products,product_length_cm,float64,32949,2,99,16.0
44,products,product_height_cm,float64,32949,2,102,10.0
45,products,product_width_cm,float64,32949,2,95,14.0
46,sellers,seller_id,str,3095,0,3095,3442f8959a84dea7ee197c632cb2df15
47,sellers,seller_zip_code_prefix,int64,3095,0,2246,13023
48,sellers,seller_city,str,3095,0,611,campinas
49,sellers,seller_state,str,3095,0,23,SP
50,translation,product_category_name,str,71,0,71,beleza_saude
51,translation,product_category_name_english,str,71,0,71,health_beauty

In [15]:
OUTPUT_PATH = PROJECT_ROOT / "data" / "raw"

data_dictionary_file = OUTPUT_PATH / "data_dictionary.csv"

data_dictionary_df.to_csv(
    data_dictionary_file,
    index=False
)

print(f"Data dictionary saved to: {data_dictionary_file}")

Data dictionary saved to: d:\cart2insights\data\raw\data_dictionary.csv

In [16]:
print("=" * 80)
print("DATA UNDERSTANDING COMPLETED")
print("=" * 80)

print(f"Datasets expected : {len(DATASETS)}")
print(f"Datasets loaded   : {len(data)}")

print("\nTables:")
for table_name, df in data.items():
    print(
        f"{table_name:20} "
        f"Rows={df.shape[0]:>8,} "
        f"Columns={df.shape[1]:>3}"
    )

print("\nNext Step:")
print("02_data_quality_analysis.ipynb")

================================================================================
DATA UNDERSTANDING COMPLETED
================================================================================
Datasets expected : 9
Datasets loaded   : 9

Tables:
customers            Rows=  99,441 Columns=  5
geolocation          Rows=1,000,163 Columns=  5
order_items          Rows= 112,650 Columns=  7
order_payments       Rows= 103,886 Columns=  5
order_reviews        Rows=  99,224 Columns=  7
orders               Rows=  99,441 Columns=  8
products             Rows=  32,951 Columns=  9
sellers              Rows=   3,095 Columns=  4
translation          Rows=      71 Columns=  2

Next Step:
02_data_quality_analysis.ipynb