In [39]:
import mysql.connector
import pandas as pd
import numpy as np
from pathlib import Path
conn = mysql.connector.connect(
    host="localhost",
    user="root",
    password="qwerty",
    database="cart2insights"
)

cursor = conn.cursor()

print("✅ Connected to MySQL successfully")

✅ Connected to MySQL successfully

In [4]:
orders = pd.read_sql(
    "SELECT * FROM orders",
    conn
)

print("Orders shape:", orders.shape)
orders.head()

C:\Users\Asus-2025\AppData\Local\Temp\ipykernel_26996\2724824435.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  orders = pd.read_sql(

Orders shape: (99163, 8)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,00010242fe8c5a6d1ba2dd792cb16214,3ce436f183e68e07877b285a838db11a,delivered,2017-09-13 08:59:02,2017-09-13 09:45:35,2017-09-19 18:34:16,2017-09-20 23:43:48,2017-09-29
1,00018f77f2f0320c557190d7a144bdd3,f6dd3ec061db4e3987629fe6b26e5cce,delivered,2017-04-26 10:53:06,2017-04-26 11:05:13,2017-05-04 14:35:00,2017-05-12 16:04:24,2017-05-15
2,000229ec398224ef6ca0657da4fc703e,6489ae5e4333f3693df5ad4372dab6d3,delivered,2018-01-14 14:33:31,2018-01-14 14:48:30,2018-01-16 12:36:48,2018-01-22 13:19:16,2018-02-05
3,00024acbcdf0a6daa1e931b038114c75,d4eb9395c8c0431ee92fce09860c5a06,delivered,2018-08-08 10:00:35,2018-08-08 10:10:18,2018-08-10 13:28:00,2018-08-14 13:32:39,2018-08-20
4,00042b26cf59d7ce69dfabb4e55b4fd9,58dbd0b2d70206bf40e62cd34e84d795,delivered,2017-02-04 13:57:51,2017-02-04 14:10:13,2017-02-16 09:46:09,2017-03-01 16:42:31,2017-03-17

In [8]:
order_items = pd.read_sql(
    "SELECT * FROM order_items",
    conn
)

print("Order items shape:", order_items.shape)
order_items.head()

C:\Users\Asus-2025\AppData\Local\Temp\ipykernel_26996\340612674.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  order_items = pd.read_sql(

Order items shape: (110476, 7)

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14

In [9]:
customers = pd.read_sql(
    "SELECT * FROM customers",
    conn
)

print("Customers shape:", customers.shape)
customers.head()

C:\Users\Asus-2025\AppData\Local\Temp\ipykernel_26996\3285358186.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  customers = pd.read_sql(

Customers shape: (99163, 5)

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,00012a2ce6f8dcda20d059ce98491703,248ffe10d632bebe4f7267f1f44844c9,06273,osasco,SP
1,000161a058600d5901f007fab4c27140,b0015e09bb4b6e47c52844fab5fb6638,35550,itapecerica,MG
2,0001fd6190edaaf884bcaf3d49edf079,94b11d37cd61cb2994a194d11f89682b,29830,nova venecia,ES
3,0002414f95344307404f0ace7a26f1d5,4893ad4ea28b2c5b3ddf4e82e79db9e6,39664,mendonca,MG
4,000379cdec625522490c315e70c7a9fb,0b83f73b19c2019e182fd552c048a22c,04841,sao paulo,SP

In [10]:
sellers = pd.read_sql(
    "SELECT * FROM sellers",
    conn
)

print("Sellers shape:", sellers.shape)
sellers.head()

Sellers shape: (3088, 4)

C:\Users\Asus-2025\AppData\Local\Temp\ipykernel_26996\1087996156.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  sellers = pd.read_sql(

,seller_id,seller_zip_code_prefix,seller_city,seller_state
0,0015a82c2db000af6aaaf3ae2ecb0532,09080,santo andre,SP
1,001cca7ae9ae17fb1caed9dfb1094831,29156,cariacica,ES
2,001e6ad469a905060d959994f1b41e4f,24754,sao goncalo,RJ
3,002100f778ceb8431b7a1020ff7ab48f,14405,franca,SP
4,003554e2dce176b5555353e4f3555ac8,74565,goiania,GO

In [11]:
payments = pd.read_sql(
    "SELECT * FROM order_payments",
    conn
)

print("Payments shape:", payments.shape)
payments.head()

C:\Users\Asus-2025\AppData\Local\Temp\ipykernel_26996\1496645639.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  payments = pd.read_sql(

Payments shape: (103599, 5)

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,credit_card,2,72.19
1,00018f77f2f0320c557190d7a144bdd3,1,credit_card,3,259.83
2,000229ec398224ef6ca0657da4fc703e,1,credit_card,5,216.87
3,00024acbcdf0a6daa1e931b038114c75,1,credit_card,2,25.78
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,credit_card,3,218.04

In [12]:
print("=" * 60)
print("FEATURE ENGINEERING DATA CHECK")
print("=" * 60)

print("Orders       :", orders.shape)
print("Order Items  :", order_items.shape)
print("Customers    :", customers.shape)
print("Sellers      :", sellers.shape)
print("Payments     :", payments.shape)

print("=" * 60)

if (
    len(orders) > 0
    and len(order_items) > 0
    and len(customers) > 0
    and len(sellers) > 0
):
    print("✅ Data is available for feature engineering")
else:
    print("❌ One or more required tables are empty")

============================================================
FEATURE ENGINEERING DATA CHECK
============================================================
Orders       : (99163, 8)
Order Items  : (110476, 7)
Customers    : (99163, 5)
Sellers      : (3088, 4)
Payments     : (103599, 5)
============================================================
✅ Data is available for feature engineering

In [13]:
date_columns = [
    "order_purchase_timestamp",
    "order_approved_at",
    "order_delivered_carrier_date",
    "order_delivered_customer_date",
    "order_estimated_delivery_date"
]

for column in date_columns:
    orders[column] = pd.to_datetime(
        orders[column],
        errors="coerce"
    )

print("✅ Date columns converted")

✅ Date columns converted

In [14]:
order_value = (
    order_items
    .groupby("order_id", as_index=False)
    .agg(
        total_order_value=("price", "sum"),
        total_freight_value=("freight_value", "sum")
    )
)

order_value["total_order_value"] = (
    order_value["total_order_value"]
    + order_value["total_freight_value"]
)

order_value = order_value[
    [
        "order_id",
        "total_order_value"
    ]
]

print("✅ Total order value calculated")

order_value.head()

✅ Total order value calculated

                           order_id  total_order_value
0  00010242fe8c5a6d1ba2dd792cb16214              72.19
1  00018f77f2f0320c557190d7a144bdd3             259.83
2  000229ec398224ef6ca0657da4fc703e             216.87
3  00024acbcdf0a6daa1e931b038114c75              25.78
4  00042b26cf59d7ce69dfabb4e55b4fd9             218.04

In [15]:
orders = orders.merge(
    order_value,
    on="order_id",
    how="left"
)

orders["total_order_value"] = (
    orders["total_order_value"]
    .fillna(0)
)

print("✅ Total order value added to orders")

orders[
    [
        "order_id",
        "total_order_value"
    ]
].head()

✅ Total order value added to orders

                           order_id  total_order_value
0  00010242fe8c5a6d1ba2dd792cb16214              72.19
1  00018f77f2f0320c557190d7a144bdd3             259.83
2  000229ec398224ef6ca0657da4fc703e             216.87
3  00024acbcdf0a6daa1e931b038114c75              25.78
4  00042b26cf59d7ce69dfabb4e55b4fd9             218.04

In [16]:
orders["delivery_days"] = (
    orders["order_delivered_customer_date"]
    - orders["order_purchase_timestamp"]
).dt.total_seconds() / (24 * 60 * 60)

print("✅ Delivery days calculated")

orders[
    [
        "order_id",
        "delivery_days"
    ]
].head()

✅ Delivery days calculated

                           order_id  delivery_days
0  00010242fe8c5a6d1ba2dd792cb16214       7.614421
1  00018f77f2f0320c557190d7a144bdd3      16.216181
2  000229ec398224ef6ca0657da4fc703e       7.948437
3  00024acbcdf0a6daa1e931b038114c75       6.147269
4  00042b26cf59d7ce69dfabb4e55b4fd9      25.114352

In [17]:
orders["delivery_delay"] = (
    orders["order_delivered_customer_date"]
    - orders["order_estimated_delivery_date"]
).dt.total_seconds() / (24 * 60 * 60)

print("✅ Delivery delay calculated")

orders[
    [
        "order_id",
        "delivery_delay"
    ]
].head()

✅ Delivery delay calculated

                           order_id  delivery_delay
0  00010242fe8c5a6d1ba2dd792cb16214       -8.011250
1  00018f77f2f0320c557190d7a144bdd3       -2.330278
2  000229ec398224ef6ca0657da4fc703e      -13.444954
3  00024acbcdf0a6daa1e931b038114c75       -5.435660
4  00042b26cf59d7ce69dfabb4e55b4fd9      -15.303808

In [18]:
orders["is_delayed"] = np.where(
    orders["delivery_delay"] > 0,
    1,
    0
)

print("✅ Delayed delivery indicator created")

orders[
    [
        "order_id",
        "delivery_delay",
        "is_delayed"
    ]
].head()

✅ Delayed delivery indicator created

                           order_id  delivery_delay  is_delayed
0  00010242fe8c5a6d1ba2dd792cb16214       -8.011250           0
1  00018f77f2f0320c557190d7a144bdd3       -2.330278           0
2  000229ec398224ef6ca0657da4fc703e      -13.444954           0
3  00024acbcdf0a6daa1e931b038114c75       -5.435660           0
4  00042b26cf59d7ce69dfabb4e55b4fd9      -15.303808           0

In [19]:
customer_order_count = (
    orders
    .groupby("customer_id")
    .agg(
        customer_order_count=("order_id", "nunique")
    )
    .reset_index()
)

print("✅ Customer order count calculated")

customer_order_count.head()

✅ Customer order count calculated

                        customer_id  customer_order_count
0  00012a2ce6f8dcda20d059ce98491703                     1
1  000161a058600d5901f007fab4c27140                     1
2  0001fd6190edaaf884bcaf3d49edf079                     1
3  0002414f95344307404f0ace7a26f1d5                     1
4  000379cdec625522490c315e70c7a9fb                     1

In [20]:
customer_spending = (
    orders
    .groupby("customer_id")
    .agg(
        customer_total_spending=(
            "total_order_value",
            "sum"
        )
    )
    .reset_index()
)

print("✅ Customer total spending calculated")

customer_spending.head()

✅ Customer total spending calculated

                        customer_id  customer_total_spending
0  00012a2ce6f8dcda20d059ce98491703                   114.74
1  000161a058600d5901f007fab4c27140                    67.41
2  0001fd6190edaaf884bcaf3d49edf079                   195.42
3  0002414f95344307404f0ace7a26f1d5                   179.35
4  000379cdec625522490c315e70c7a9fb                   107.01

In [21]:
customer_spending = (
    orders
    .groupby("customer_id")
    .agg(
        customer_total_spending=(
            "total_order_value",
            "sum"
        )
    )
    .reset_index()
)

print("✅ Customer total spending calculated")

customer_spending.head()

✅ Customer total spending calculated

                        customer_id  customer_total_spending
0  00012a2ce6f8dcda20d059ce98491703                   114.74
1  000161a058600d5901f007fab4c27140                    67.41
2  0001fd6190edaaf884bcaf3d49edf079                   195.42
3  0002414f95344307404f0ace7a26f1d5                   179.35
4  000379cdec625522490c315e70c7a9fb                   107.01

In [22]:
customer_aov = (
    orders
    .groupby("customer_id")
    .agg(
        average_order_value=(
            "total_order_value",
            "mean"
        )
    )
    .reset_index()
)

print("✅ Customer average order value calculated")

customer_aov.head()

✅ Customer average order value calculated

                        customer_id  average_order_value
0  00012a2ce6f8dcda20d059ce98491703               114.74
1  000161a058600d5901f007fab4c27140                67.41
2  0001fd6190edaaf884bcaf3d49edf079               195.42
3  0002414f95344307404f0ace7a26f1d5               179.35
4  000379cdec625522490c315e70c7a9fb               107.01

In [23]:
repeat_customers = (
    customer_order_count
    .copy()
)

repeat_customers["repeat_customer"] = np.where(
    repeat_customers["customer_order_count"] > 1,
    1,
    0
)

print("✅ Repeat customer indicator created")

repeat_customers.head()

✅ Repeat customer indicator created

                        customer_id  customer_order_count  repeat_customer
0  00012a2ce6f8dcda20d059ce98491703                     1                0
1  000161a058600d5901f007fab4c27140                     1                0
2  0001fd6190edaaf884bcaf3d49edf079                     1                0
3  0002414f95344307404f0ace7a26f1d5                     1                0
4  000379cdec625522490c315e70c7a9fb                     1                0

In [24]:
seller_revenue = (
    order_items
    .groupby("seller_id")
    .agg(
        seller_revenue=("price", "sum")
    )
    .reset_index()
)

print("✅ Seller revenue calculated")

seller_revenue.head()

✅ Seller revenue calculated

                          seller_id  seller_revenue
0  0015a82c2db000af6aaaf3ae2ecb0532         2685.00
1  001cca7ae9ae17fb1caed9dfb1094831        25080.03
2  001e6ad469a905060d959994f1b41e4f          250.00
3  002100f778ceb8431b7a1020ff7ab48f         1234.50
4  004c9cd9d87a3c30c522c48c4fc07416        17841.69

In [25]:
seller_order_count = (
    order_items
    .groupby("seller_id")
    .agg(
        seller_order_count=("order_id", "nunique")
    )
    .reset_index()
)

print("✅ Seller order count calculated")

seller_order_count.head()

✅ Seller order count calculated

                          seller_id  seller_order_count
0  0015a82c2db000af6aaaf3ae2ecb0532                   3
1  001cca7ae9ae17fb1caed9dfb1094831                 200
2  001e6ad469a905060d959994f1b41e4f                   1
3  002100f778ceb8431b7a1020ff7ab48f                  51
4  004c9cd9d87a3c30c522c48c4fc07416                 147

In [26]:
seller_features = sellers.merge(
    seller_revenue,
    on="seller_id",
    how="left"
)

seller_features = seller_features.merge(
    seller_order_count,
    on="seller_id",
    how="left"
)

seller_features["seller_revenue"] = (
    seller_features["seller_revenue"]
    .fillna(0)
)

seller_features["seller_order_count"] = (
    seller_features["seller_order_count"]
    .fillna(0)
)

print("✅ Seller feature dataset created")

seller_features.head()

✅ Seller feature dataset created

,seller_id,seller_zip_code_prefix,seller_city,seller_state,seller_revenue,seller_order_count
0,0015a82c2db000af6aaaf3ae2ecb0532,09080,santo andre,SP,2685.00,3.0
1,001cca7ae9ae17fb1caed9dfb1094831,29156,cariacica,ES,25080.03,200.0
2,001e6ad469a905060d959994f1b41e4f,24754,sao goncalo,RJ,250.00,1.0
3,002100f778ceb8431b7a1020ff7ab48f,14405,franca,SP,1234.50,51.0
4,003554e2dce176b5555353e4f3555ac8,74565,goiania,GO,0.00,0.0

In [27]:
customer_features = customers.merge(
    customer_order_count,
    on="customer_id",
    how="left"
)

customer_features = customer_features.merge(
    customer_spending,
    on="customer_id",
    how="left"
)

customer_features = customer_features.merge(
    customer_aov,
    on="customer_id",
    how="left"
)

customer_features = customer_features.merge(
    repeat_customers[
        [
            "customer_id",
            "repeat_customer"
        ]
    ],
    on="customer_id",
    how="left"
)

customer_features["customer_order_count"] = (
    customer_features["customer_order_count"]
    .fillna(0)
)

customer_features["customer_total_spending"] = (
    customer_features["customer_total_spending"]
    .fillna(0)
)

customer_features["average_order_value"] = (
    customer_features["average_order_value"]
    .fillna(0)
)

customer_features["repeat_customer"] = (
    customer_features["repeat_customer"]
    .fillna(0)
)

print("✅ Customer feature dataset created")

customer_features.head()

✅ Customer feature dataset created

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state,customer_order_count,customer_total_spending,average_order_value,repeat_customer
0,00012a2ce6f8dcda20d059ce98491703,248ffe10d632bebe4f7267f1f44844c9,06273,osasco,SP,1,114.74,114.74,0
1,000161a058600d5901f007fab4c27140,b0015e09bb4b6e47c52844fab5fb6638,35550,itapecerica,MG,1,67.41,67.41,0
2,0001fd6190edaaf884bcaf3d49edf079,94b11d37cd61cb2994a194d11f89682b,29830,nova venecia,ES,1,195.42,195.42,0
3,0002414f95344307404f0ace7a26f1d5,4893ad4ea28b2c5b3ddf4e82e79db9e6,39664,mendonca,MG,1,179.35,179.35,0
4,000379cdec625522490c315e70c7a9fb,0b83f73b19c2019e182fd552c048a22c,04841,sao paulo,SP,1,107.01,107.01,0

In [28]:
order_features = orders[
    [
        "order_id",
        "customer_id",
        "order_status",
        "order_purchase_timestamp",
        "order_approved_at",
        "order_delivered_carrier_date",
        "order_delivered_customer_date",
        "order_estimated_delivery_date",
        "total_order_value",
        "delivery_days",
        "delivery_delay",
        "is_delayed"
    ]
].copy()

print("✅ Order feature dataset created")

order_features.head()

✅ Order feature dataset created

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,total_order_value,delivery_days,delivery_delay,is_delayed
0,00010242fe8c5a6d1ba2dd792cb16214,3ce436f183e68e07877b285a838db11a,delivered,2017-09-13 08:59:02,2017-09-13 09:45:35,2017-09-19 18:34:16,2017-09-20 23:43:48,2017-09-29,72.19,7.614421,-8.011250,0
1,00018f77f2f0320c557190d7a144bdd3,f6dd3ec061db4e3987629fe6b26e5cce,delivered,2017-04-26 10:53:06,2017-04-26 11:05:13,2017-05-04 14:35:00,2017-05-12 16:04:24,2017-05-15,259.83,16.216181,-2.330278,0
2,000229ec398224ef6ca0657da4fc703e,6489ae5e4333f3693df5ad4372dab6d3,delivered,2018-01-14 14:33:31,2018-01-14 14:48:30,2018-01-16 12:36:48,2018-01-22 13:19:16,2018-02-05,216.87,7.948437,-13.444954,0
3,00024acbcdf0a6daa1e931b038114c75,d4eb9395c8c0431ee92fce09860c5a06,delivered,2018-08-08 10:00:35,2018-08-08 10:10:18,2018-08-10 13:28:00,2018-08-14 13:32:39,2018-08-20,25.78,6.147269,-5.435660,0
4,00042b26cf59d7ce69dfabb4e55b4fd9,58dbd0b2d70206bf40e62cd34e84d795,delivered,2017-02-04 13:57:51,2017-02-04 14:10:13,2017-02-16 09:46:09,2017-03-01 16:42:31,2017-03-17,218.04,25.114352,-15.303808,0

In [29]:
order_features = order_features.merge(
    customer_features[
        [
            "customer_id",
            "customer_order_count",
            "customer_total_spending",
            "average_order_value",
            "repeat_customer"
        ]
    ],
    on="customer_id",
    how="left"
)

print("✅ Customer features added to orders")

order_features.head()

✅ Customer features added to orders

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,total_order_value,delivery_days,delivery_delay,is_delayed,customer_order_count,customer_total_spending,average_order_value,repeat_customer
0,00010242fe8c5a6d1ba2dd792cb16214,3ce436f183e68e07877b285a838db11a,delivered,2017-09-13 08:59:02,2017-09-13 09:45:35,2017-09-19 18:34:16,2017-09-20 23:43:48,2017-09-29,72.19,7.614421,-8.011250,0,1,72.19,72.19,0
1,00018f77f2f0320c557190d7a144bdd3,f6dd3ec061db4e3987629fe6b26e5cce,delivered,2017-04-26 10:53:06,2017-04-26 11:05:13,2017-05-04 14:35:00,2017-05-12 16:04:24,2017-05-15,259.83,16.216181,-2.330278,0,1,259.83,259.83,0
2,000229ec398224ef6ca0657da4fc703e,6489ae5e4333f3693df5ad4372dab6d3,delivered,2018-01-14 14:33:31,2018-01-14 14:48:30,2018-01-16 12:36:48,2018-01-22 13:19:16,2018-02-05,216.87,7.948437,-13.444954,0,1,216.87,216.87,0
3,00024acbcdf0a6daa1e931b038114c75,d4eb9395c8c0431ee92fce09860c5a06,delivered,2018-08-08 10:00:35,2018-08-08 10:10:18,2018-08-10 13:28:00,2018-08-14 13:32:39,2018-08-20,25.78,6.147269,-5.435660,0,1,25.78,25.78,0
4,00042b26cf59d7ce69dfabb4e55b4fd9,58dbd0b2d70206bf40e62cd34e84d795,delivered,2017-02-04 13:57:51,2017-02-04 14:10:13,2017-02-16 09:46:09,2017-03-01 16:42:31,2017-03-17,218.04,25.114352,-15.303808,0,1,218.04,218.04,0

In [31]:
order_item_features = order_item_features.merge(
    seller_features[
        [
            "seller_id",
            "seller_revenue",
            "seller_order_count"
        ]
    ],
    on="seller_id",
    how="left"
)

print("✅ Seller features added to order items")

order_item_features.head()

✅ Seller features added to order items

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,item_total_value,seller_revenue,seller_order_count
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29,72.19,12271.71,138.0
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93,259.83,7952.43,104.0
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87,216.87,3280.00,12.0
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79,25.78,1049.22,12.0
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14,218.04,3661.18,28.0

In [32]:
numeric_columns = [
    "total_order_value",
    "delivery_days",
    "delivery_delay",
    "customer_order_count",
    "customer_total_spending",
    "average_order_value",
    "repeat_customer",
    "is_delayed"
]

for column in numeric_columns:
    if column in order_features.columns:
        order_features[column] = (
            order_features[column]
            .fillna(0)
        )

numeric_columns_items = [
    "price",
    "freight_value",
    "item_total_value",
    "seller_revenue",
    "seller_order_count"
]

for column in numeric_columns_items:
    if column in order_item_features.columns:
        order_item_features[column] = (
            order_item_features[column]
            .fillna(0)
        )

print("✅ Missing numeric values handled")

✅ Missing numeric values handled

In [33]:
print("=" * 70)
print("FEATURE ENGINEERING SUMMARY")
print("=" * 70)

print("\nOrder Features:")
print(order_features.shape)

print("\nCustomer Features:")
print(customer_features.shape)

print("\nSeller Features:")
print(seller_features.shape)

print("\nOrder Item Features:")
print(order_item_features.shape)

print("=" * 70)

print("\nCreated features:")

features_created = [
    "Total order value",
    "Delivery days",
    "Delivery delay",
    "Delayed delivery indicator",
    "Customer order count",
    "Customer total spending",
    "Average order value",
    "Repeat customer indicator",
    "Seller revenue",
    "Seller order count"
]

for feature in features_created:
    print("✅", feature)

======================================================================
FEATURE ENGINEERING SUMMARY
======================================================================

Order Features:
(99163, 16)

Customer Features:
(99163, 9)

Seller Features:
(3088, 6)

Order Item Features:
(110476, 10)
======================================================================

Created features:
✅ Total order value
✅ Delivery days
✅ Delivery delay
✅ Delayed delivery indicator
✅ Customer order count
✅ Customer total spending
✅ Average order value
✅ Repeat customer indicator
✅ Seller revenue
✅ Seller order count

In [34]:
order_features[
    [
        "total_order_value",
        "delivery_days",
        "delivery_delay",
        "customer_order_count",
        "customer_total_spending",
        "average_order_value",
        "repeat_customer"
    ]
].describe()

,total_order_value,delivery_days,delivery_delay,customer_order_count,customer_total_spending,average_order_value,repeat_customer
count,99163.000000,99163.000000,99163.000000,99163.0,99163.000000,99163.000000,99163.0
mean,156.863674,12.176251,-10.851096,1.0,156.863674,156.863674,0.0
std,219.314271,9.637883,10.209991,0.0,219.314271,219.314271,0.0
min,0.000000,0.000000,-146.016123,1.0,0.000000,0.000000,0.0
25%,58.820000,6.294751,-16.158241,1.0,58.820000,58.820000,0.0
50%,102.560000,10.027130,-11.331215,1.0,102.560000,102.560000,0.0
75%,174.855000,15.350330,-6.168270,1.0,174.855000,174.855000,0.0
max,13664.080000,209.628611,188.975081,1.0,13664.080000,13664.080000,0.0

In [35]:
delay_summary = (
    order_features["is_delayed"]
    .value_counts()
    .rename(
        index={
            0: "On Time",
            1: "Delayed"
        }
    )
)

print(delay_summary)

is_delayed
On Time    91365
Delayed     7798
Name: count, dtype: int64

In [36]:
repeat_summary = (
    customer_features["repeat_customer"]
    .value_counts()
    .rename(
        index={
            0: "One-time Customer",
            1: "Repeat Customer"
        }
    )
)

print(repeat_summary)

repeat_customer
One-time Customer    99163
Name: count, dtype: int64

In [40]:
feature_path = "feature_engineered_data"

Path(feature_path).mkdir(
    exist_ok=True
)

order_features.to_csv(
    f"{feature_path}/order_features.csv",
    index=False
)

customer_features.to_csv(
    f"{feature_path}/customer_features.csv",
    index=False
)

seller_features.to_csv(
    f"{feature_path}/seller_features.csv",
    index=False
)

order_item_features.to_csv(
    f"{feature_path}/order_item_features.csv",
    index=False
)

print("✅ Feature datasets saved successfully")

✅ Feature datasets saved successfully